export const CONFIGS = {
    SYSTEM: {
        TICK_INTERVAL_MS: 1000,
        FAST_TICK_INTERVAL_MS: 40,
        BULK_BUY_AMOUNTS: [1, 10, 100, 1000],
    },
    UNLOCKS: {
        SORT_GARBAGE_IN_UNSORTED_WASTE: 10,
        SORTING_PANEL_IN_MONEY: 25,
        ORGANIZER_LOGISTIC: 5,
        TOTAL_EMPLOYEES_FOR_COST: 5,
    },
    BALANCE: {
        BASE_GARBAGE_CAPACITY: 100,
        BASE_UNSORTED_CAPACITY: 1000,
    },
}
