export const CONFIGS = {
    SYSTEM: {
        TICK_INTERVAL_MS: 1000,
        FAST_TICK_INTERVAL_MS: 40,
        BULK_BUY_AMOUNTS: [1, 10, 100, 1000],
    },
    UNLOCKS: {
        SORT_GARBAGE_IN_UNSORTED_WASTE: 10,
        ORGANIZER_LOGISTIC: 5,
        TOTAL_EMPLOYEES_FOR_COST: 5,
    },
    BALANCE: {
        BASE_UNSORTED_CAPACITY: 100,
        BASE_GARBAGE_CAPACITY: 75,
        BASE_RECYCLABLES_CAPACITY: 25,
    },
    EMPLOYEES: {
        BASE_EMPLOYEE_PAY: 0.1,
    },
}
